# -*- coding: utf-8 -*-
"""ML_gang.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lyKlzsQFONmGeCgLtXw3fJtOaLgnJEN6

Data Preprocessing
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

tr_ident = pd.read_csv('/content/drive/My Drive/ML Gang/data/train_identity.csv', engine='python')

# Explore shape and features of the identity data
print(tr_ident.shape)
print(tr_ident.head)
print(tr_ident.columns)

tr_trans = pd.read_csv('/content/drive/My Drive/ML Gang/data/train_transaction.csv', engine='python')

# Explore shape and features of the transaction data
print(tr_trans.shape)
print(tr_trans.head)
print(tr_trans.columns)

ts_ident = pd.read_csv('/content/drive/My Drive/ML Gang/data/test_identity.csv', engine='python')

ts_trans = pd.read_csv('/content/drive/My Drive/ML Gang/data/test_transaction.csv', engine='python')

"""## Identify Invalid/Null Values"""

